name: tests-payments

on:
  pull_request:
    paths:
      - 'server/payments/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd server/payments && npm install && npm run test:ci
